- apt: update_cache=yes

- name: Install nginx
  apt: pkg={{item}} state=installed
  with_items:
   - nginx

- name: Stop apache2
  shell: service {{item}} stop
  with_items:
   - apache2

- name: Disable default nginx config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  register: nginx_default_config

- name: Install/update nginx config for DEVELOPMENT catsite
  copy: src=nginx-catsite dest=/etc/nginx/sites-enabled/catsite
  register: nginx_catsite_config
  when: production != "yes"

- name: Install/update nginx config for PRODUCTION catsite
  copy: src=nginx-proxy dest=/etc/nginx/sites-enabled/catsite
  register: nginx_catsite_config
  when: production == "yes"

- name: Reload nginx configuration
  shell: service nginx reload
  when: nginx_default_config.changed or nginx_catsite_config.changed

- name: Install/update catsite
  copy: src=catsite dest=/var/www/
  
